server:
  port: 8000

spring:
  application:
    name: barren
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题
  # 配置Redis
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000
  # 配置Cache
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时


# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: auto
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 打印SQL
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


auth:
  # 配置 秘钥
  secret-key: barren
  # 配置 oauth2 客户端
  clients:
    - clientId: app
      clientSecret: 123456
    - clientId: web
      clientSecret: barren
  # 登录配置
  login:

